# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frm', models.DateTimeField()),
                ('until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Type of Food')),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('availability', models.ManyToManyField(to='LunchCloud.Availability')),
                ('blacklist', models.ManyToManyField(to='LunchCloud.FoodType')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchCloud.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchCloud.Profile'),
        ),
    ]
