# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 15:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchCloud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodtype',
            name='name',
        ),
        migrations.AddField(
            model_name='foodtype',
            name='Type of Food',
            field=models.CharField(default='whoops', max_length=80),
        ),
    ]
