# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-18 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchCloud', '0003_auto_20171018_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Invitation Code'),
        ),
    ]
