# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-19 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunchCloud', '0005_auto_20171019_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='availability',
            field=models.ManyToManyField(blank=True, to='LunchCloud.Availability'),
        ),
    ]
