# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-19 05:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LunchCloud', '0006_auto_20171019_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='whitelist',
            field=models.ManyToManyField(related_name='whitelisted_by', to='LunchCloud.FoodType'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='blacklist',
            field=models.ManyToManyField(blank=True, related_name='blacklisted_by', to='LunchCloud.FoodType'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invited_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='LunchCloud.Profile'),
        ),
    ]
