# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-19 05:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LunchCloud', '0007_auto_20171019_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='LunchCloud.Profile'),
        ),
    ]
