# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-10-20 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LunchCloud', '0008_auto_20171019_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='LunchEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateField()),
                ('frm', models.TimeField()),
                ('until', models.TimeField()),
                ('min_attendees', models.SmallIntegerField(verbose_name='Min number of attendees')),
                ('max_attendees', models.SmallIntegerField(verbose_name='Max number of attendees')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('allow_evaluation', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('Proposed', 'proposed'), ('Confirmed', 'confirmed'), ('Rejected', 'rejected'), ('Awaiting Evaluation', 'awaiting'), ('Done', 'done')], default='proposed', max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='invitationcode',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Invitation Code'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whitelist',
            field=models.ManyToManyField(blank=True, related_name='whitelisted_by', to='LunchCloud.FoodType'),
        ),
        migrations.AddField(
            model_name='lunchevents',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='attended', to='LunchCloud.Profile'),
        ),
        migrations.AddField(
            model_name='lunchevents',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunchCloud.Profile'),
        ),
        migrations.AddField(
            model_name='lunchevents',
            name='invitees',
            field=models.ManyToManyField(related_name='invited_to', to='LunchCloud.Profile'),
        ),
    ]
